name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lua tools
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux-x86_64.zip -o stylua.zip
          unzip -o stylua.zip -d /usr/local/bin
      - name: Luacheck
        run: luacheck resources
      - name: StyLua check
        run: stylua --check resources
      - name: Validate fxmanifest
        run: |
          if ! grep -R "fx_version" -n resources; then
            echo "Missing fxmanifest in a resource"; exit 1; fi
      - name: SQL dry-run
        run: |
          if [ -f docs/MIGRATIONS.sql ]; then
            echo "Lint only: ensure MIGRATIONS.sql exists"; fi


