name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install luacheck
        run: luarocks install luacheck
      - name: Run luacheck
        run: |
          luacheck resources --no-color --codes --formatter TAP || true

  validate-fxmanifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate fxmanifests exist
        run: |
          test -f server.cfg
          find resources -name fxmanifest.lua -print | tee /dev/stderr | grep -q fxmanifest.lua

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install UI deps if present
        run: |
          set -e
          if [ -f resources/[cfx]/chat/web/package.json ]; then
            cd resources/[cfx]/chat/web && pnpm i && pnpm build
          fi
          if [ -f resources/[ox]/ox_lib/web/package.json ]; then
            cd resources/[ox]/ox_lib/web && pnpm i && pnpm build
          fi

